version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    command: ["python", "./Application.py"]
  frontend:
    build: ./Application
    ports:
      - "3000:3000"
    command: ["npm", "start"]